workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS for Device
        script: flutter build ios --release
